global:
  scrape_interval: 10s  # fr√©quence de collecte (toutes les 10 secondes)

scrape_configs:
  # --- Kafka ---
  - job_name: 'kafka'
    static_configs:
    - targets: ['bigdataproject-kafka-1:7071']

  # --- NiFi ---
  - job_name: 'nifi'
    metrics_path: /nifi-api/metrics
    static_configs:
      - targets: ['bigdataproject-nifi-1:8080']

  # --- Spark ---
  - job_name: 'spark'
    static_configs:
      - targets: ['bigdataproject-spark-1:4040']

  # --- MinIO ---
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['bigdataproject-minio-1:9000']
